- name: Update apt
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - tar

- name: Create prometheus user
  user:
    name: prometheus
    shell: /sbin/nologin

- name: Download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.51.2/prometheus-2.51.2.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Move prometheus binary
  command: mv /opt/prometheus-2.51.2.linux-amd64/prometheus /usr/local/bin/

- name: Move promtool binary
  command: mv /opt/prometheus-2.51.2.linux-amd64/promtool /usr/local/bin/

- name: Create Prometheus service
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      User=prometheus
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/opt/prometheus-2.51.2.linux-amd64/prometheus.yml \
        --storage.tsdb.path=/opt/prometheus-2.51.2.linux-amd64/data

      [Install]
      WantedBy=multi-user.target

- name: Start Prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started
